### ISSUE TITLE
cmds

### ISSUE THREAD

**Issue by yair100** [WalkingCat/SymDiff#1]
What is the difference between -n, -o and -ns, -os?

**Comment by MagicAndre1981** [comment]
ns = new symbol path, os = old symbol path:

https://github.com/WalkingCat/SymDiff/blob/master/symdiff/symdiff.cpp#L18

**Comment by WalkingCat** [comment]
if -n/-o points to PE image (exe/dll) files or folders containing PE files, symdiff will try to find the matching PDB symbol files in the (-ns/-os) symbol paths, you could download PDB symbols first using tools like SymChk.

**Comment by Biswa96** [comment]
What to do if pdb present in a folder?

**Comment by ATecSolution** [comment]
symdiff -ns newsymbol.pdb -os oldsymbol.pdb

**Comment by WalkingCat** [comment]
> 
> 
> What to do if pdb present in a folder?

if -n/-o points to PDB files or folders containing PDB files, then symdiff will compare them, and (-ns/-os) symbol paths have no effects and will be ignored

**Comment by Biswa96** [comment]
Feature request:
1. show some error when msdia140.dll isn't present in `%PATH%` or executable folder.
2. Add some docs in readme.
3. Group 'added' and 'removed' change in separate section, if possible.
4. There are some unknown character (shown as ? character) in output. Maybe console error.

**Comment by ATecSolution** [comment]
is this a good command for symchck? symchk /r c:\windows\system32 /s SRV*c:\symbols\*http://msdl.microsoft.com/download/symbols

**Comment by WalkingCat** [comment]
> 
> 
> Feature request:
> 
>     1. show some error when msdia140.dll isn't present in `%PATH%` or executable folder.
> 
>     2. Add some docs in readme.
> 
>     3. Group 'added' and 'removed' change in separate section, if possible.
> 
>     4. There are some unknown character (shown as ? character) in output. Maybe console error.

1, will do
2, will do
3, nope I think mixing them together often makes it more obivous and clear what changed
4, hmm... unlikely, maybe mangled symbols ?

**Comment by WalkingCat** [comment]
> 
> 
> is this a good command for symchck? symchk /r c:\windows\system32 /s SRV*c:\symbols*http://msdl.microsoft.com/download/symbols

yes, this is what I meant. and I recommend to use -op to see the progress :-)

**Comment by Biswa96** [comment]
> 4, hmm... unlikely, maybe mangled symbols ?

For my [WslReverse](https://github.com/Biswa96/WslReverse) project, I used your tool with LxssManager.pdb file. The diff output shows those characters. Also it shows many long names with `dtor` and `ctor`.

`ENABLE_VIRTUAL_TERMINAL_PROCESSING` may help.

**Comment by WalkingCat** [comment]
ok I will look into this
